[package]
name = "structuredvg_macros"
version = "0.1.0"
edition = "2021"
description = "Macros for structuredvg"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
